### ISSUE TITLE
pip install issue

### ISSUE THREAD

**Issue by trollerxoxo** [building-energy/gbxml#2]
Hi,
Today I tried to pip install gbxml. However, I keep getting this error message:
```
ERROR: Could not find a version that satisfies the requirement gbxml (from versions: none)
ERROR: No matching distribution found for gbxml
```
Why am I facing this issue?
Thanks a lot in advance

**Comment by stevenkfirth** [comment]
Unfortunately this is an unfinished package which I'm no longer working on. However feel free to use the code here for your own work.

The readme file is incorrect - `pip install gbxml` will not work as the package was never loaded up to the PyPi index and so pip cannot find it.

You could make this work by downloading or cloning this git repository to your local PC and then doing a local `pip install` such as shown here: https://stackoverflow.com/questions/15031694/installing-python-packages-from-local-file-system-folder-to-virtualenv-with-pip

I will update the readme file to remove the `pip instal gbxml` instructions.
